In [1]:
import numpy as np
from scipy import stats

## 1. The historical average score in a certification exam is 65. A training institute introduces a new course. A random sample of 50 students trained under the new course has a mean score of 68 and a standard deviation of 10. At the 5% level of significance, test whether the new course improves  performance.

In [2]:
sample = np.random.normal(loc = 65, scale = 10, size = 50).astype("int")
sample

array([39, 83, 59, 57, 55, 70, 75, 59, 62, 58, 69, 73, 69, 70, 61, 62, 63,
       64, 70, 53, 75, 64, 68, 52, 54, 66, 58, 60, 77, 65, 75, 66, 54, 58,
       70, 64, 65, 58, 77, 63, 53, 83, 46, 49, 55, 68, 63, 57, 69, 49])

In [3]:
t_stat, p_value_two_tailed = stats.ttest_1samp(a = sample, popmean = 65)
t_stat, p_value_two_tailed

(np.float64(-1.498059429402272), np.float64(0.14053275965381087))

In [4]:
p_value_one_tailed = p_value_two_tailed / 2
p_value_one_tailed

np.float64(0.07026637982690544)

In [5]:
print("t-statistic:", t_stat)
print("p-value (one-tailed):", p_value_one_tailed)

t-statistic: -1.498059429402272
p-value (one-tailed): 0.07026637982690544


In [6]:
alpha = 0.05
if (t_stat > 0) and (p_value_one_tailed < alpha):
    print("Reject H0 → Course improves performance")
else:
    print("Fail to reject H0")

Fail to reject H0


### 2. A company claims that the average time taken to resolve customer tickets is 30 minutes. A random sample of 40 tickets shows a mean resolution time of 33 minutes with a standard deviation of 8 minutes. At the 5% level of significance, test whether the average resolution time has increased.

In [57]:
observations_40_tickets = np.random.normal(loc = 33, scale = 5, size = 40).astype("int")
observations_40_tickets

array([25, 40, 42, 38, 32, 27, 38, 30, 39, 34, 37, 34, 36, 33, 41, 33, 35,
       42, 26, 26, 37, 27, 42, 30, 29, 42, 40, 42, 37, 28, 42, 31, 37, 37,
       32, 36, 37, 34, 27, 34])

In [58]:
t_stats,p_value = stats.ttest_1samp(a= observations_40_tickets, popmean = 30, alternative = 'greater')
t_stats,p_value

(np.float64(5.699959678316108), np.float64(6.759907135340432e-07))

In [59]:
p_value = p_value/2 

In [60]:
if p_value < 0.05:
    print("We Reject H0")
else:
    print("We consider H1")

We Reject H0


## 3. A company claims that 60% of its users are satisfied with its product. In a survey of 200 users, 134 users report satisfaction. At the 5% level of significance, test whether customer satisfaction is higher than claimed.

In [7]:
from statsmodels.stats.proportion import proportions_ztest

In [8]:
z_stat, p_value_two_tailed = proportions_ztest(count = 134, nobs = 200, value= 0.60)
z_stat, p_value_two_tailed

(np.float64(2.105322668110795), np.float64(0.0352632302175221))

In [9]:
p_value_one_tailed = p_value_two_tailed / 2
p_value_one_tailed

np.float64(0.01763161510876105)

In [10]:
print("z-statistic:", z_stat)
print("p-value (one-tailed):", p_value_one_tailed)

z-statistic: 2.105322668110795
p-value (one-tailed): 0.01763161510876105


In [11]:
alpha = 0.05
if (z_stat > 0) and (p_value_one_tailed < alpha):
    print("Reject H0 → Satisfaction is higher than claimed")
else:
    print("Fail to reject H0")

Reject H0 → Satisfaction is higher than claimed


## 4.	Historically, 40% of applicants pass an entrance test. After a new preparation program, 90 out of 180 applicants pass. At the 5% level of significance, test whether the pass rate has improved.

In [12]:
z_stat, p_value_two_tailed = proportions_ztest(count = 90, nobs = 180, value= 0.40)
z_stat, p_value_two_tailed

(np.float64(2.683281572999747), np.float64(0.0072903580915356595))

In [13]:
p_value_one_tailed = p_value_two_tailed / 2
p_value_one_tailed

np.float64(0.0036451790457678298)

In [14]:
print("z-statistic:", z_stat)
print("p-value (one-tailed):", p_value_one_tailed)

z-statistic: 2.683281572999747
p-value (one-tailed): 0.0036451790457678298


In [15]:
alpha = 0.05
if (z_stat > 0) and (p_value_one_tailed < alpha):
    print("Reject H0 → Pass rate has improved")
else:
    print("Fail to reject H0")

Reject H0 → Pass rate has improved


## 5. Two teaching methods are used to train employees. A sample of 30 employees trained using Method A has a mean score of 75 with a standard deviation of 12. A sample of 28 employees trained using Method B has a mean score of 70 with a standard deviation of 10. At the 5% level of significance, test whether there is a difference in average scores between the two methods.

In [16]:
np.random.seed(0)
sample1 = np.random.normal(loc = 75, scale = 12, size = 30).astype("int")
sample2 = np.random.normal(loc = 70, scale = 10, size = 28).astype("int")

In [17]:
print(sample1)
print(sample2)

[ 96  79  86 101  97  63  86  73  73  79  76  92  84  76  80  79  92  72
  78  64  44  82  85  66 102  57  75  72  93  92]
[71 73 61 50 66 71 82 82 66 66 59 55 52 89 64 65 57 77 53 67 61 73 64 58
 69 74 70 73]


In [18]:
t_stat, p_value_two_tailed = stats.ttest_ind(a = sample1, b = sample2)
t_stat, p_value_two_tailed

(np.float64(4.311056517187383), np.float64(6.64325249943344e-05))

In [19]:
print("t-statistic:", t_stat)
print("p-value:", p_value_two_tailed)

t-statistic: 4.311056517187383
p-value: 6.64325249943344e-05


In [20]:
alpha = 0.05
if p_value_two_tailed < alpha:
    print("Reject H0 → There is a difference")
else:
    print("Fail to reject H0")

Reject H0 → There is a difference


### 6. The average delivery time from two warehouses is compared using random samples. Warehouse A has a sample of 35 deliveries with a mean time of 48 minutes and a standard deviation of 6 minutes. Warehouse B has a sample of 40 deliveries with a mean time of 52 minutes and a standard deviation of 7 minutes. At the 5% level of significance, test whether the mean delivery times differ.

In [24]:
np.random.seed(0)
sample1 = np.random.normal(loc = 48, scale = 6, size = 35).astype("int")
sample2 = np.random.normal(loc = 52, scale = 7, size = 40).astype("int")

In [25]:
print(sample1)
print(sample2)

[58 50 53 61 59 42 53 47 47 50 48 56 52 48 50 50 56 46 49 42 32 51 53 43
 61 39 48 46 57 56 48 50 42 36 45]
[53 60 60 49 49 44 42 40 65 48 48 43 57 40 50 45 54 48 43 51 54 52 54 47
 49 47 49 46 39 53 49 40 55 45 52 57 52 59 43 54]


In [26]:
t_stat, p_value_two_tailed = stats.ttest_ind(a = sample1, b = sample2)
t_stat, p_value_two_tailed

(np.float64(-0.2471781192715037), np.float64(0.8054642262846214))

In [27]:
print("t-statistic:", t_stat)
print("p-value:", p_value_two_tailed)

t-statistic: -0.2471781192715037
p-value: 0.8054642262846214


In [29]:
alpha = 0.05
if p_value_two_tailed < alpha:
    print("Reject H0 → Delivery times differ")
else:
    print("Fail to reject H0")

Fail to reject H0


### 7. Two versions of a website are tested. Out of 500 users for Version A, 320 users click the signup button. Out of 480 users for Version B, 290 users click the signup button. At the 5% level of significance, test whether the conversion rates differ.

In [32]:
import numpy as np
from statsmodels.stats.proportion import proportions_ztest

# Given data
count = np.array([320, 290])
nobs = np.array([500, 480])

# Two-proportion z-test
z_stat, p_value_two_tailed = proportions_ztest(count, nobs)

print("z-statistic:", z_stat)
print("p-value:", p_value_two_tailed)

# Decision
alpha = 0.05
if p_value_two_tailed < alpha:
    print("Reject H0 → Conversion rates differ")
else:
    print("Fail to reject H0")

z-statistic: 1.1567515462334546
p-value: 0.24737388327470267
Fail to reject H0


### 8.	A vaccine is tested in two regions. In Region A, 180 out of 300 people recover. In Region B, 165 out of 310 people recover. At the 5% level of significance, test whether the recovery rates are significantly different.

In [34]:
import numpy as np
from statsmodels.stats.proportion import proportions_ztest

# Given data
count = np.array([180, 165])
nobs = np.array([300, 310])

# Two-proportion z-test
z_stat, p_value_two_tailed = proportions_ztest(count, nobs)

print("z-statistic:", z_stat)
print("p-value:", p_value_two_tailed)

# Decision
alpha = 0.05
if p_value_two_tailed < alpha:
    print("Reject H0 → Recovery rates differ")
else:
    print("Fail to reject H0")

z-statistic: 1.6874523112864297
p-value: 0.09151641239095082
Fail to reject H0


### 9.	A company wants to compare the average productivity of employees trained using three different training programs. Program A has 25 employees with a mean productivity score of 80 and a standard deviation of 8. Program B has 30 employees with a mean of 75 and a standard deviation of 7. Program C has 28 employees with a mean of 82 and a standard deviation of 6. At the 5% level of significance, test whether there is a difference in mean productivity across the programs.

In [39]:
np.random.seed(0)

A = np.random.normal(loc = 80, scale = 8, size = 25).astype("int")
B = np.random.normal(loc = 75, scale = 7, size = 30).astype("int")
C = np.random.normal(loc = 82, scale = 6, size = 28).astype("int")

In [40]:
print(A)
print(B)
print(C)

[94 83 87 97 94 72 87 78 79 83 81 91 86 80 83 82 91 78 82 73 59 85 86 74
 98]
[64 75 73 85 85 76 77 68 61 72 76 83 83 72 72 67 65 63 88 71 71 66 80 63
 73 68 77 71 66 74]
[84 82 83 78 79 77 79 77 71 83 79 72 84 76 82 86 82 88 74 84 77 76 78 80
 82 75 87 84]


In [41]:
f_stat, p_value = stats.f_oneway(A,B,C)
f_stat, p_value

(np.float64(16.750987098141724), np.float64(8.384223751264438e-07))

In [42]:
print("F-statistic:", f_stat)
print("p-value:", p_value)

F-statistic: 16.750987098141724
p-value: 8.384223751264438e-07


In [43]:
alpha = 0.05
if p_value < alpha:
    print("Reject H0 → Productivity differs")
else:
    print("Fail to reject H0")

Reject H0 → Productivity differs


### 10.	A company wants to test whether gender and product preference are independent. The survey results are as follows:
-	Male: 60 prefer Product A, 40 prefer Product B
-	Female: 50 prefer Product A, 50 prefer Product B

**At the 5% level of significance, test for independence.**


In [48]:
import numpy as np
from scipy.stats import chi2_contingency

observed = np.array([[60, 40],
                     [50, 50]])

chi_stat, p_value, dof, expected = chi2_contingency(observed)

print("Chi-square:", chi_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print("Reject H0 → Dependent")
else:
    print("Fail to reject H0 → Independent")

Chi-square: 1.6363636363636362
p-value: 0.20082512269514174
Fail to reject H0 → Independent


### 11.	A  hospital studies whether smoking status is related to disease occurrence. The data collected is as follows:

- Smokers: 70 have the disease, 30 do not
- Non-smokers: 40 have the disease, 60 do not

**At the 5% level of significance, test whether smoking status and disease occurrence are independent.**


In [50]:
observations = np.array([[70,30],
                         [40,60]])
observations

array([[70, 30],
       [40, 60]])

In [52]:
chi_stat, p_value, dof, expected = chi2_contingency(observations)
chi_stat, p_value, dof, expected

(np.float64(16.98989898989899),
 np.float64(3.7579211012441855e-05),
 1,
 array([[55., 45.],
        [55., 45.]]))

In [53]:
print("Chi-square:", chi_stat)
print("p-value:", p_value)

Chi-square: 16.98989898989899
p-value: 3.7579211012441855e-05


In [54]:
if p_value < 0.05:
    print("Reject H0 → Dependent")
else:
    print("Fail to reject H0 → Independent")

Reject H0 → Dependent


### 12.	A dice manufacturer claims that a die is fair. The die is rolled 120 times, and the observed frequencies are:
-	Face 1: 18
-	Face 2: 22
-	Face 3: 20
-	Face 4: 25
-	Face 5: 17
-	Face 6: 18

**At the 5% level of significance, test whether the die is fair.**


In [69]:
import numpy as np
from scipy.stats import chisquare

In [70]:
observation = np.array([18,22,20,25,17,18]) 
observation

array([18, 22, 20, 25, 17, 18])

In [71]:
expectation = np.full(6, observation.sum() / 6)
expectation

array([20., 20., 20., 20., 20., 20.])

In [73]:
chi_stat, p_value = chisquare(observation,expectation)
chi_stat, p_value

(np.float64(2.3000000000000003), np.float64(0.8062668698851285))

In [74]:
print("Chi-square:", chi_stat)
print("p-value:", p_value)

Chi-square: 2.3000000000000003
p-value: 0.8062668698851285


In [75]:
if p_value < 0.05:
    print("Reject H0 → Not fair")
else:
    print("Fail to reject H0 → Fair die")

Fail to reject H0 → Fair die
